[workspace]
authors = ["udit-asopa <udit.asopa@gmail.com>"]
channels = ["conda-forge"]
name = "data-science-assignment-nosto"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
nosto_pred = "python main.py"

[dependencies]
python = "3.12.*"
pandas = ">=3.0.1,<4"
numpy = ">=2.4.2,<3"
pathlib = ">=1.0.1,<2"
typer = ">=0.24.0,<0.25"
jupyter = ">=1.1.1,<2"
python-dateutil = ">=2.9.0,<3"
matplotlib = ">=3.10.8,<4"
scikit-learn = ">=1.8.0,<2"
xgboost = ">=3.2.0,<4"
lightgbm = ">=4.6.0,<5"
